### ISSUE TITLE
Add web config editor

### ISSUE THREAD

**Issue by dracco1993** [RAR1741/PITS#2]
As a programmer, I want a web config editor, so that I don't have to mess with all that file transfer shenanigans.

- [x] Pull config from robot
- [x] Display config in GUI
- [x] Push config to robot

**Comment by tricktrap** [comment]
You are crazy, but yes, that'd be awesome. :+1:

**Comment by dracco1993** [comment]
I may be crazy, but it's going to happen.  :+1:

**Comment by dracco1993** [comment]
Fully implemented in de929fb50a3bb468ee0e58b70ccdad738a60948b
